name: Quality Gate
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:
permissions: read-all
jobs:
  security-scan:
    if: ${{ github.event.pull_request.draft == false }}
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          output_file_path: console
          quiet: true

  rust-tests:
    if: ${{ github.event.pull_request.draft == false }}
    name: Rust Core Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --test '*' --verbose

  python-tests:
    if: ${{ github.event.pull_request.draft == false }}
    name: Python Plugin Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'tests/python/requirements.txt'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/python/requirements.txt
          pip install -r plugins/shared/python/requirements.txt

      - name: Run Python plugin tests
        run: |
          pytest tests/python/ -v --tb=short
